<?php

$items = $block->getCategoryProductCollection();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$imageHelper  = $objectManager->get('\Magento\Catalog\Helper\Image');
$review =  $this->getLayout()->createBlock('Magento\Catalog\Block\Product\AbstractProduct');
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$type = 'widget-product-grid'; ?>

<!-- <div class="wrapper">
    <h2>Slick Carousel Example<h2>
        <div class="carousel" style="width: 30%;">
            <div><img src="http://lorempixel.com/200/200/nature/"></div>
            <div><img src="http://lorempixel.com/200/200/fashion/"></div>
            <div><img src="http://lorempixel.com/200/200/sports/"></div>
            <div><img src="http://lorempixel.com/200/200/animal/"></div>
            <div><img src="http://lorempixel.com/200/200/abstract/"></div>
            <div><img src="http://lorempixel.com/200/200/people/"></div>
        </div>
</div>-->


<div class="product-intro owl-carousel">
    <?php foreach ($items as $product) :
        $image_url = $imageHelper->init($product, 'product_base_image')->setImageFile($product->getFile())->getUrl();
    ?>
        <div class="item">

            <figure>
                <a href="<?= $product->getProductUrl() ?>">
                    <img src="<?= $image_url ?>">
                </a>
                <!-- Discount -->
                <?php $finalPrice = $product->getFinalPrice();
                $price = $product->getPrice();
                if ($finalPrice < $price) { ?>
                    <span class="discount_percent1">
                        <?php
                        $saving = round(($finalPrice / $price) * 100) - 100;
                        echo $saving . "%"; ?>
                    </span>
                <?php } ?>
                <!-- -->
            </figure>


            <div class="product-details">
                <div class="product-title">
                    <a href="product.html"><?php echo $product->getName(); ?></a>
                </div>
                <?php if (!empty($review->getReviewsSummaryHtml($product, $templateType, false))) { ?>
                    <div class="ratings-container">
                        <div class="product-ratings">
                            <span class="ratings" id="sao" style="width:100%"><?php echo $review->getReviewsSummaryHtml($product, $templateType, false); ?></span><!-- End .ratings -->
                        </div>
                        <!-- End .product-ratings -->
                    </div>
                <?php } ?>
                <!-- No stars -->
                <?php if ((int)$product->getReviewsCount() == 0) : ?>
                    <div class="abcd">
                        <div class="rating-summary" id="rating-summary-none">
                            <div class="rating-result" title="0%">
                                <span style="width: 0%;"><span>0%</span></span>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
                <!-- -->
                <!-- End .product-container -->
                <div class="price-box">
                    <span class="product-price"><?= $block->getProductPriceHtml($product, $type); ?></span>
                </div><!-- End .price-box -->
            </div><!-- End .product-details -->
        </div>
    <?php endforeach; ?>
</div>




<script type="text/javascript">
 require(["jquery", "owl-carousel"],function($) {
        $(document).ready(function() {
            // console.log(123123)
            $('.owl-carousel').owlCarousel({
                loop:true,
                margin:10,
                responsiveClass:true,
                navText: [
                    '<span class="prev-btn"><i class="fas fa-chevron-left" style="font-size: 20px; color: #727272;"></i></span>',
                    '<span class="next-btn"><i class="fas fa-chevron-right" style="font-size: 20px; color: #727272;"></i></span>'
                ],
                responsive:{
                    0:{
                        items:2,
                        nav:true,
                        loop:false
                    },
                    426:{
                        items:2,
                        nav:true,
                        loop:false
                    },
                    1000:{
                        items:4,
                        nav:true,
                        loop:false
                    }
                }
            })
        });
    });
    // require(["jquery"], function($) {
    //     // $('.carousel').slick({
    //     //     slidesToShow: 3,
    //     //     dots: true,
    //     //     centerMode: true,
    //     // });
    //     // $(".product-intro").slick({
    //     //     autoplay: false,
    //     //     autoplaySpeed: 2500,
    //     //     dots: true,
            
    //     //     speed: 300,
    //     //     slidesToShow: 5,
    //     //     slidesToScroll: 1,
    //     //     responsive: [{
    //     //             breakpoint: 768, // 600x800
    //     //             settings: {
    //     //                 slidesToShow: 3
    //     //             }
    //     //         },
    //     //         {
    //     //             breakpoint: 600, // 480x320
    //     //             settings: {
    //     //                 slidesToShow: 2
    //     //             }
    //     //         },
    //     //         {
    //     //             breakpoint: 480, // 320x480
    //     //             settings: {
    //     //                 slidesToShow: 1
    //     //             }
    //     //         }
    //     //     ]
    //     // });
    //     //     $('.owl-carousel').owlCarousel({
    //     //     loop: true,
    //     //     items: 5, 
    //     //     nav: true,
    //     //     autoplay:false,
    //     //     autoplayTimeout:1000,
    //     //     autoplayHoverPause:true,
    //     //     dots: true,
    //     //     navText : ["<i class='fas fa-chevron-left'></i>","<i class='fas fa-chevron-right'></i>"],
    //     //     itemsDesktop : [1199,3],
    //     //     itemsDesktopSmall : [900,3], // betweem 900px and 601px
    //     //     itemsTablet: [700,2], // 2 items between 600 and 480
    //     //     itemsMobile : [479,1] , // 1 item between 479 and 0
    //     //     responsiveClass:true,
    //     //     responsive:{
    //     //         0:{
    //     //             items:2,
    //     //             nav:true
    //     //         },
    //     //         600:{
    //     //             items:3,
    //     //             nav:false
    //     //         },
    //     //         1000:{
    //     //             items:5,
    //     //             nav:true,
    //     //             loop:false
    //     //         }
    //     //     }
    //     // });
    //     $('.carousel').slick({
    //         dots: true,
    //         infinite: false,
    //         speed: 300,
    //         slidesToShow: 4,
    //         slidesToScroll: 1,
    //         responsive: [
    //             {
    //             breakpoint: 1024,
    //             settings: {
    //                 slidesToShow: 3,
    //                 slidesToScroll: 3,
    //                 infinite: true,
    //                 dots: true
    //             }
    //             },
    //             {
    //             breakpoint: 600,
    //             settings: {
    //                 slidesToShow: 2,
    //                 slidesToScroll: 2
    //             }
    //             },
    //             {
    //             breakpoint: 480,
    //             settings: {
    //                 slidesToShow: 1,
    //                 slidesToScroll: 1
    //             }
    //             }
    //             // You can unslick at a given breakpoint now by adding:
    //             // settings: "unslick"
    //             // instead of a settings object
    //         ]
    //         });
    // });
</script>