<section>
    <div class="home-banner height-x3">
        <figure>
            <img src=”<?php echo $this->getViewFileUrl(‘images/banner-bellow.jpg’); ?>”>
        </figure>
        <div class="banner-content col-xl-11 full-content">
            <div class="container">
                <div class="left-content">
                    <div>
                        <span>it is time for a</span>
                        <h4>Modern Bathroom</h4>
                    </div>
                    <button class="btn">shop now <i class="fas fa-long-arrow-alt-right"></i></button>
                </div>
                <div class="banner-info">
                    <a href="#" class="btn skew-box">Exclusive COUPON</a>
                    <h3 class="sale-off skew-box"><span>$200</span>off</h3>
                </div>
            </div>
        </div>
    </div>
</section>
