<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" rel="stylesheet" />
<div class="social-link">
    <h4>Questions?</h4>
    <div class="links">
        <a href="#" class="phone_link">1-888-123-456</a>
        <hr class="vertical">
        <div class="social-icons">
            <a href="#" target="_blank" class="social-icon"><i class="fab fa-facebook-f"></i>
            <a href="#" target="_blank" class="social-icon"><i class="fab fa-twitter"></i></a>
            <a href="#" target="_blank" class="social-icon"><i class="fab fa-linkedin-in"></i></i></a>
            <a href="#" target="_blank" class="social-icon"><i class="fab fa-instagram"></i></a>
        </div>
    </div>
</div>