<div class="menu">
    <div class="menu__column">
        <p><?php echo __('Account')?></p>
        <ul>
            <li><a href="#"><?php echo __('My Account')?></a></li>
            <li><a href="#"><?php echo __('Track Your Order')?></a></li>
            <li><a href="#"><?php echo __('Payment Methods')?></a></li>
            <li><a href="#"><?php echo __('Shipping Guide')?></a></li>
        </ul>
    </div>
    <div class="menu__column">
        <p><?php echo __('About')?></p>
        <ul>
            <li><a href="#" title="<?php echo __('About Porto')?>"><?php echo __('About Porto')?></a></li>
            <li><a href="#" title="<?php echo __('Our Guarantees')?>"><?php echo __('Our Guarantees')?></a></li>
            <li><a href="#" title="<?php echo __('Terms And Conditions')?>"><?php echo __('Terms And Conditions')?></a></li>
            <li><a href="#" title="<?php echo __('Privacy Policy')?>"><?php echo __('Privacy Policy')?></a></li>
        </ul>
    </div>
    <div class="menu__column">
        <p><?php echo __('Features')?></p>
        <ul>
            <li><a href="#" title="<?php echo __('Powerful Admin Panel')?>"><?php echo __('Powerful Admin Panel')?></a></li>
            <li><a href="#" title="<?php echo __('Mobile & Retina Optimized')?>"><?php echo __('Mobile & Retina Optimized')?></a></li>
            <li><a href="#" title="<?php echo __('Super Fast Porto Theme')?>"><?php echo __('Super Fast Porto Theme')?></a></li>
            <li><a href="#" title="<?php echo __('1st Fully working Ajax Theme')?>"><?php echo __('1st Fully working Ajax Theme')?></a></li>
        </ul>
    </div>
</div>
